CREATE DATABASE myinfo

CREATE TABLE sir(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255),
    adress VARCHAR(255),
    emailadress VARCHAR(255),
    section VARCHAR(255),
    contact VARCHAR(16)
);